// DAX Query
DEFINE
	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('Product'[Brand], "IsGrandTotalRowTotal"),
			"Sales_Amount", 'Sales'[Sales Amount],
			"Margin__", 'Sales'[Margin %],
			"Total_Cost", 'Sales'[Total Cost],
			"Total_Quantity", 'Sales'[Total Quantity]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'Product'[Brand], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC, 'Product'[Brand]
